# **1. Linear Layer**

* 신경망의 가장 기본 구성 요소
* Fully-connected(FC) Layer라고 불리기도 함
* 내부 파라미터에 따른 선형 변환을 수행하는 함수

# **2. Linear Layer 작동 방식**

* 각 입력 노드들에 weight(가중치)를 곱하고 모두 합친 뒤, bias(편향)을 더함
* 행렬 곱으로 구현 가능
* n차원에서 m차원으로 선형 변환 함수

<font color=red>* Linear Layer는 선형 변환 함수</font> 

<font color=red>*  내부 가중치 파라미터(weight parameter) W와 b에 의해 정의</font>

<font color=red>* 이 함수의 파라미터를 잘 조절하면 주어진 입력에 대해 원하는 출력을 만들 수 있음</font>

In [1]:
import torch

In [3]:
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

In [4]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [5]:
def linear(x, W, b):
  y = torch.matmul(x, W) + b
  return y

In [6]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])
print(x.size())

torch.Size([4, 3])


In [7]:
y = linear(x, W, b)

In [8]:
print(y.size())

torch.Size([4, 2])


# **3. nn.Module**

In [10]:
# nn 만들 때 상속받아서 사용하는 추상 클래스
import torch.nn as nn

In [12]:
class MyLinear(nn.Module):
  def __init__(self, input_dim=3, output_dim=2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()

    self.W = torch.FloatTensor(input_dim, output_dim)
    self.b = torch.FloatTensor(output_dim)
  
  def forward(self, x):
    y = torch.matmul(x, self.W) + self.b
    return y

In [13]:
linear = MyLinear(3, 2)
y = linear(x) # forward가 자동으로 호출. 

In [15]:
print(y.size())

torch.Size([4, 2])


In [17]:
for p in linear.parameters():
  print(p) # parameters 출력이 안됨

### **nn.Parameter**

In [18]:
class MyLinear(nn.Module):
  def __init__(self, input_dim=3, output_dim=2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()

    self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
    self.b = nn.Parameter(torch.FloatTensor(output_dim))
  
  def forward(self, x):
    y = torch.matmul(x, self.W) + self.b
    return y

In [19]:
linear = MyLinear(3, 2)
y = linear(x)

In [20]:
print(y.size())

torch.Size([4, 2])


In [21]:
for p in linear.parameters():
  print(p)

Parameter containing:
tensor([[6.9628e-31, 3.0864e-41],
        [6.4460e-44, 1.1210e-43],
        [1.3593e-43, 1.5975e-43]], requires_grad=True)
Parameter containing:
tensor([6.9629e-31, 3.0864e-41], requires_grad=True)


### **nn.Module의 Linear함수를 통해 재구현**

In [22]:
class MyLinear(nn.Module):
  def __init__(self, input_dim=3, output_dim=2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()

    self.linear = nn.Linear(input_dim, output_dim)
  
  def forward(self, x):
    y = self.linear(x)
    return y

In [23]:
linear = MyLinear(3, 2)
y = linear(x)

In [24]:
print(y.size())

torch.Size([4, 2])


In [25]:
for p in linear.parameters():
  print(p)

Parameter containing:
tensor([[-0.3925,  0.4751,  0.2113],
        [-0.0552,  0.4741,  0.5035]], requires_grad=True)
Parameter containing:
tensor([0.4292, 0.3981], requires_grad=True)
