# **1. GPU 사용하는 방법**

In [3]:
import torch
import torch.nn as nn

In [5]:
x = torch.cuda.FloatTensor(2, 2) 
# 에러가 발생할 경우 런타임->런타임 유형변경에서 GPU를 선택
print(x)
# GPU가 여러개 있는 경우 GPU 번호를 확인
# 같은 디바이스에 있는 텐서끼리만 연산이 가능

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')


In [6]:
x = torch.FloatTensor(2, 2)
print(x)

tensor([[1.6045e+02, 3.0637e-41],
        [4.4842e-44, 0.0000e+00]])


In [7]:
# GPU로 보냄
x.cuda()

tensor([[1.6045e+02, 3.0637e-41],
        [4.4842e-44, 0.0000e+00]], device='cuda:0')

In [8]:
# GPU0으로 지정
d = torch.device('cuda:0')

In [9]:
# move가 아니라 copy로 됨
x.cuda(device=d)

tensor([[1.6045e+02, 3.0637e-41],
        [4.4842e-44, 0.0000e+00]], device='cuda:0')

In [10]:
x.device

device(type='cpu')

# **2. Convert to CPU tensor from CUDA tensor**

In [11]:
x = torch.cuda.FloatTensor(2, 2)

In [12]:
x = x.cpu()

In [13]:
d = torch.device('cpu')
x = x.to(d)

# **3. Move model from CPU to GPU**

In [14]:
def print_params(model):
  for p in model.parameters():
    print(p)

In [15]:
linear = nn.Linear(2, 2)
print_params(linear)

Parameter containing:
tensor([[-0.1865, -0.6113],
        [-0.5616, -0.0387]], requires_grad=True)
Parameter containing:
tensor([-0.1846,  0.3608], requires_grad=True)


In [16]:
linear = linear.cuda()
print_params(linear)

Parameter containing:
tensor([[-0.1865, -0.6113],
        [-0.5616, -0.0387]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.1846,  0.3608], device='cuda:0', requires_grad=True)


In [18]:
linear = linear.cpu()
print_params(linear)

Parameter containing:
tensor([[-0.1865, -0.6113],
        [-0.5616, -0.0387]], requires_grad=True)
Parameter containing:
tensor([-0.1846,  0.3608], requires_grad=True)


In [19]:
d = torch.device('cuda:0')
linear = linear.to(d)
print_params(linear)

Parameter containing:
tensor([[-0.1865, -0.6113],
        [-0.5616, -0.0387]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.1846,  0.3608], device='cuda:0', requires_grad=True)


In [20]:
linear.device # 모델은 device attribute 를 제공하지 않음

AttributeError: ignored

In [21]:
x = torch.cuda.FloatTensor(2, 2)

In [22]:
x.new(2, 2) # x와 같은 타입이면서 같은 디바이스에 있는 텐서를 만듬

tensor([[0.0000, 1.5596],
        [0.5616, 0.0387]], device='cuda:0')

In [23]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [24]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [25]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

> 다른 device에 있는 텐서끼리는 연산할 수 없음