# **1. Pytorch**

* Pytorch는 tensorflow와 함께 딥러닝에서 가장 널리 사용되는 framework
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 python기반으로 변경한 것이 Pytorch임
* New York 대학교와 Facebook이 공동으로 만들었고, 가장 대중적으로 널리 사용되는 framework임

# **2. Pytorch import**

In [1]:
import torch
print(torch.__version__)

1.10.0+cu111


### **2-1. Tensor**

* 텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조
* Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)함

In [2]:
# list로부터 직접 tensor 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
import numpy as np

In [4]:
# numpy array로부터 tensor 생성
np_array = np.array(data)
x_np_1 = torch.tensor(np_array) # 카피를 만듬(새로운 텐서, 메모리낭비)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_np_2 = torch.as_tensor(np_array) # 뷰를 만듬
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [6]:
x_np_3 = torch.from_numpy(np_array) # 뷰를 만듬
print(x_np_3)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_np_1[0, 0] = 5
print(x_np_1)
print(np_array)

tensor([[5, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [8]:
x_np_2[0, 0] = 6
print(x_np_2)
print(np_array)

tensor([[6, 2],
        [3, 4]])
[[6 2]
 [3 4]]


In [9]:
x_np_3[0, 0] = 7
print(x_np_3)
print(np_array)

tensor([[7, 2],
        [3, 4]])
[[7 2]
 [3 4]]


In [10]:
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[5 2]
 [3 4]] <class 'numpy.ndarray'>


In [11]:
a = torch.ones(2, 3)
print(a)
b = torch.zeros(2, 3)
print(b)
c = torch.full((2, 3), 2)
print(c)
d = torch.empty(2, 3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[5.1243e+27, 3.0680e-41, 3.3631e-44],
        [0.0000e+00,        nan, 1.0000e+00]])


In [12]:
e = torch.zeros_like(c)
print(e)
f = torch.ones_like(c)
print(f)
g = torch.full_like(c, 3)
print(g)
h = torch.empty_like(c)
print(h)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[     94035851376640,                  24,          4294967295],
        [8171062582517395298, 8243662592152856949, 7310305785198503009]])


In [13]:
i = torch.eye(3)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
j = torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
k = torch.rand(2, 2)
l = torch.randn(2, 2)
print(k)
print(l)

tensor([[0.2320, 0.0713],
        [0.8827, 0.8998]])
tensor([[-0.7739,  0.0099],
        [-0.2546, -0.5097]])


### **2-2. Tensor 속성**

In [16]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'DataType of tensor: {tensor.dtype}')
print(f'Device tensor : {tensor.device}')

Shape of tensor: torch.Size([3, 4])
DataType of tensor: torch.float32
Device tensor : cpu


In [19]:
# 속성 변경
tensor = tensor.reshape(4, 3)
tensor = tensor.int()
if torch.cuda.is_available():
  tensor = tensor.to('cuda') # 확인 !

print(f'Shape of tensor: {tensor.shape}')
print(f'DataType of tensor: {tensor.dtype}')
print(f'Device tensor : {tensor.device}') # 확인 !

Shape of tensor: torch.Size([4, 3])
DataType of tensor: torch.int32
Device tensor : cuda:0


### **2-3. Indexing과 Slicing**

In [20]:
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [21]:
# indexing
print(a[1])
print(a[0, -1])

tensor([5, 6, 7, 8])
tensor(4)


In [24]:
# slicing
print(a[1:-1])
print(a[:2, 2:])

tensor([[5, 6, 7, 8]])
tensor([[3, 4],
        [7, 8]])


### **2-4. Transpose**

In [26]:
a = torch.arange(16).reshape(2, 2, 4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [27]:
b = a.transpose(1, 2)
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [28]:
c = a.permute((2, 0, 1))
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### **2-5 Tensor 연산**

In [31]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [33]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)
print('😎'*30)
print(torch.add(x, y))
print(torch.subtract(x, y))
print(torch.multiply(x, y))
print(torch.divide(x, y))
print(torch.matmul(x, y))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [38]:
# in-place 연산
print(x.add(y))
print(x)

print(x.add_(y)) # x에 결과가 다시 저장
print(x)

tensor([[16., 20.],
        [24., 28.]])
tensor([[11., 14.],
        [17., 20.]])
tensor([[16., 20.],
        [24., 28.]])
tensor([[16., 20.],
        [24., 28.]])


In [39]:
z = torch.arange(1, 11).reshape(2, 5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [40]:
sum1 = torch.sum(z, axis=0)
sum2 = torch.sum(z, axis=1)
sum3 = torch.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [41]:
a = torch.arange(24).reshape(4, 6)
b = a.clone().detach()
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])


In [42]:
c = torch.cat([a, b], axis=0)
print(c, c.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([8, 6])


In [43]:
c = torch.cat([a, b], axis=-1)
print(c, c.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]]) torch.Size([4, 12])


# **3. Pytorch로 구현한 손글씨**

In [44]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
import numpy as np

In [48]:
## MNIST Data down

# 공개 데이터셋에서 학습 데이터를 내려받음
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

# 공개 데이터셋에서 테스트 데이터를 내려받음
test_data = datasets.MNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

In [50]:
batch_size = 64

# 데이터로더를 생성, 텐서에서는 데이터셋
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
  print("Shape of X [N, C, H, W]: ", X.shape)
  print("Shape of y: ", y.shape, y.dtype)
  break 

Shape of X [N, C, H, W]:  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64


In [54]:
# 학습에 사용할 CPU나 GPU장치를 얻음
device = 'cuda' if torch.cuda.is_available() else "cpu"
print("Using {} device".format(device))

# 모델을 정의
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 128),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(128, 10)
    )
  
  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits
  
model = NeuralNetwork().to(device)
print(model)

Using cuda device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=128, out_features=10, bias=True)
  )
)


In [56]:
# Loss 함수와 Optimizer 설정
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [57]:
# Training을 위한 함수
def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  for batch, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)

    # 예측 오류 계산
    pred = model(X)
    loss = loss_fn(pred, y)

    # 역전파
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
      loss, current = loss.item(), batch * len(X)
      print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")